### ISSUE TITLE
I have taken 'class EtherCard' has no member named 'mymask' error

### ISSUE THREAD

**Issue by cosonaller** [Clement87/PushingBox-for-Arduino-ENC28J60#2]
Hi
I have taken 'class EtherCard' has no member named 'mymask' error. I am pursuing on the that error

**Comment by consolacion** [comment]
I think by now it should be ether.mymask

**Comment by ced8rol** [comment]
![capture d ecran 30](https://user-images.githubusercontent.com/41305820/45917688-954e6d80-be7b-11e8-98d5-eca2bc5f1a7f.png)
I have this problem. Somebody can help me?
